
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eth-batch
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: market
  source:
    repoURL: http://gitlab.mgmt.an2.shd.naemo.io/mona/eth-batch-helm.git
    targetRevision: stage
    path: .
    helm:
     valueFiles:
     - ./stg/values.yaml
  destination:
    server: https://E1590B0C4B7CF0087E8224BE91AFDECA.gr7.us-east-2.eks.amazonaws.com
    namespace: eth-batch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
    syncOptions:
     - CreateNamespace=true